  const ITEMS = [
        // === Greek (lower) ===
        { cat: 'Greek (thường)', code: '\\alpha', display: '\\alpha', desc: 'alpha' },
        { cat: 'Greek (thường)', code: '\\beta', display: '\\beta', desc: 'beta' },
        { cat: 'Greek (thường)', code: '\\gamma', display: '\\gamma', desc: 'gamma' },
        { cat: 'Greek (thường)', code: '\\delta', display: '\\delta', desc: 'delta' },
        { cat: 'Greek (thường)', code: '\\epsilon', display: '\\epsilon', desc: 'epsilon' },
        { cat: 'Greek (thường)', code: '\\varepsilon', display: '\\varepsilon', desc: 'epsilon cong' },
        { cat: 'Greek (thường)', code: '\\zeta', display: '\\zeta', desc: 'zeta' },
        { cat: 'Greek (thường)', code: '\\eta', display: '\\eta', desc: 'eta' },
        { cat: 'Greek (thường)', code: '\\theta', display: '\\theta', desc: 'theta' },
        { cat: 'Greek (thường)', code: '\\vartheta', display: '\\vartheta', desc: 'theta biến thể' },
        { cat: 'Greek (thường)', code: '\\iota', display: '\\iota', desc: 'iota' },
        { cat: 'Greek (thường)', code: '\\kappa', display: '\\kappa', desc: 'kappa' },
        { cat: 'Greek (thường)', code: '\\lambda', display: '\\lambda', desc: 'lambda' },
        { cat: 'Greek (thường)', code: '\\mu', display: '\\mu', desc: 'mu' },
        { cat: 'Greek (thường)', code: '\\nu', display: '\\nu', desc: 'nu' },
        { cat: 'Greek (thường)', code: '\\xi', display: '\\xi', desc: 'xi' },
        { cat: 'Greek (thường)', code: '\\pi', display: '\\pi', desc: 'pi' },
        { cat: 'Greek (thường)', code: '\\varpi', display: '\\varpi', desc: 'pi biến thể' },
        { cat: 'Greek (thường)', code: '\\rho', display: '\\rho', desc: 'rho' },
        { cat: 'Greek (thường)', code: '\\varrho', display: '\\varrho', desc: 'rho biến thể' },
        { cat: 'Greek (thường)', code: '\\sigma', display: '\\sigma', desc: 'sigma (cuối từ dùng \\varsigma)' },
        { cat: 'Greek (thường)', code: '\\varsigma', display: '\\varsigma', desc: 'sigma tận cùng' },
        { cat: 'Greek (thường)', code: '\\tau', display: '\\tau', desc: 'tau' },
        { cat: 'Greek (thường)', code: '\\upsilon', display: '\\upsilon', desc: 'upsilon' },
        { cat: 'Greek (thường)', code: '\\phi', display: '\\phi', desc: 'phi' },
        { cat: 'Greek (thường)', code: '\\varphi', display: '\\varphi', desc: 'phi cong' },
        { cat: 'Greek (thường)', code: '\\chi', display: '\\chi', desc: 'chi' },
        { cat: 'Greek (thường)', code: '\\psi', display: '\\psi', desc: 'psi' },
        { cat: 'Greek (thường)', code: '\\omega', display: '\\omega', desc: 'omega' },

        // === Greek (upper) ===
        { cat: 'Greek (hoa)', code: '\\Gamma', display: '\\Gamma', desc: 'Gamma' },
        { cat: 'Greek (hoa)', code: '\\Delta', display: '\\Delta', desc: 'Delta' },
        { cat: 'Greek (hoa)', code: '\\Theta', display: '\\Theta', desc: 'Theta' },
        { cat: 'Greek (hoa)', code: '\\Lambda', display: '\\Lambda', desc: 'Lambda' },
        { cat: 'Greek (hoa)', code: '\\Xi', display: '\\Xi', desc: 'Xi' },
        { cat: 'Greek (hoa)', code: '\\Pi', display: '\\Pi', desc: 'Pi' },
        { cat: 'Greek (hoa)', code: '\\Sigma', display: '\\Sigma', desc: 'Sigma' },
        { cat: 'Greek (hoa)', code: '\\Upsilon', display: '\\Upsilon', desc: 'Upsilon' },
        { cat: 'Greek (hoa)', code: '\\Phi', display: '\\Phi', desc: 'Phi' },
        { cat: 'Greek (hoa)', code: '\\Psi', display: '\\Psi', desc: 'Psi' },
        { cat: 'Greek (hoa)', code: '\\Omega', display: '\\Omega', desc: 'Omega' },

        // === Operators ===
        { cat: 'Toán tử', code: '\\pm', display: '\\pm', desc: '± cộng trừ' },
        { cat: 'Toán tử', code: '\\mp', display: '\\mp', desc: '∓ trừ cộng' },
        { cat: 'Toán tử', code: '\\cdot', display: '\\cdot', desc: 'tích chấm' },
        { cat: 'Toán tử', code: '\\times', display: '\\times', desc: 'nhân ×' },
        { cat: 'Toán tử', code: '\\div', display: '\\div', desc: 'chia ÷' },
        { cat: 'Toán tử', code: '\\ast', display: '\\ast', desc: '* sao' },
        { cat: 'Toán tử', code: '\\star', display: '\\star', desc: '⋆ sao rỗng' },
        { cat: 'Toán tử', code: '\\circ', display: '\\circ', desc: '∘ tròn nhỏ' },
        { cat: 'Toán tử', code: '\\oplus', display: '\\oplus', desc: '⊕ tổng trực tiếp' },
        { cat: 'Toán tử', code: '\\otimes', display: '\\otimes', desc: '⊗ tích tensor' },
        { cat: 'Toán tử', code: '\\oslash', display: '\\oslash', desc: '⊘' },
        { cat: 'Toán tử', code: '\\cup', display: '\\cup', desc: 'hợp ∪' },
        { cat: 'Toán tử', code: '\\cap', display: '\\cap', desc: 'giao ∩' },
        { cat: 'Toán tử', code: '\\setminus', display: '\\setminus', desc: 'hiệu tập \\ ' },
        { cat: 'Toán tử', code: '\\vee', display: '\\vee', desc: '∨ OR logic' },
        { cat: 'Toán tử', code: '\\wedge', display: '\\wedge', desc: '∧ AND logic' },
        { cat: 'Toán tử', code: '\\neg', display: '\\neg', desc: '¬ NOT' },

        // === Relations ===
        { cat: 'Quan hệ', code: '=', display: '=', desc: 'bằng' },
        { cat: 'Quan hệ', code: '\\neq', display: '\\neq', desc: 'khác ≠' },
        { cat: 'Quan hệ', code: '\\approx', display: '\\approx', desc: 'xấp xỉ ≈' },
        { cat: 'Quan hệ', code: '\\sim', display: '\\sim', desc: 'tương tự ∼' },
        { cat: 'Quan hệ', code: '\\propto', display: '\\propto', desc: 'tỉ lệ ∝' },
        { cat: 'Quan hệ', code: '<', display: '<', desc: 'nhỏ hơn' },
        { cat: 'Quan hệ', code: '>', display: '>', desc: 'lớn hơn' },
        { cat: 'Quan hệ', code: '\\le', display: '\\le', desc: '≤ nhỏ hơn hoặc bằng' },
        { cat: 'Quan hệ', code: '\\ge', display: '\\ge', desc: '≥ lớn hơn hoặc bằng' },
        { cat: 'Quan hệ', code: '\\ll', display: '\\ll', desc: '≪ rất nhỏ hơn' },
        { cat: 'Quan hệ', code: '\\gg', display: '\\gg', desc: '≫ rất lớn hơn' },
        { cat: 'Quan hệ', code: '\\subset', display: '\\subset', desc: '⊂ tập con nghiêm' },
        { cat: 'Quan hệ', code: '\\subseteq', display: '\\subseteq', desc: '⊆ tập con' },
        { cat: 'Quan hệ', code: '\\supset', display: '\\supset', desc: '⊃ chứa nghiêm' },
        { cat: 'Quan hệ', code: '\\supseteq', display: '\\supseteq', desc: '⊇ chứa' },
        { cat: 'Quan hệ', code: '\\in', display: '\\in', desc: '∈ thuộc' },
        { cat: 'Quan hệ', code: '\\notin', display: '\\notin', desc: '∉ không thuộc' },
        { cat: 'Quan hệ', code: '\\ni', display: '\\ni', desc: '∋ chứa phần tử' },
        { cat: 'Quan hệ', code: '\\equiv', display: '\\equiv', desc: '≡ đồng dư/đồng nhất' },
        { cat: 'Quan hệ', code: '\\cong', display: '\\cong', desc: '≅ bằng nhau (hình học)' },
        { cat: 'Quan hệ', code: '\\simeq', display: '\\simeq', desc: '≃ xấp xỉ/tương đương' },
        { cat: 'Quan hệ', code: '\\Rightarrow', display: '\\Rightarrow', desc: '⇒ suy ra' },
        { cat: 'Quan hệ', code: '\\Leftarrow', display: '\\Leftarrow', desc: '⇐ suy từ' },
        { cat: 'Quan hệ', code: '\\Leftrightarrow', display: '\\Leftrightarrow', desc: '⇔ tương đương' },

        // === Arrows ===
        { cat: 'Mũi tên', code: '\\to', display: '\\to', desc: '→' },
        { cat: 'Mũi tên', code: '\\gets', display: '\\gets', desc: '←' },
        { cat: 'Mũi tên', code: '\\mapsto', display: '\\mapsto', desc: '↦' },
        { cat: 'Mũi tên', code: '\\leftrightarrow', display: '\\leftrightarrow', desc: '↔' },
        { cat: 'Mũi tên', code: '\\uparrow', display: '\\uparrow', desc: '↑' },
        { cat: 'Mũi tên', code: '\\downarrow', display: '\\downarrow', desc: '↓' },
        { cat: 'Mũi tên', code: '\\nearrow', display: '\\nearrow', desc: '↗' },
        { cat: 'Mũi tên', code: '\\searrow', display: '\\searrow', desc: '↘' },
        { cat: 'Mũi tên', code: '\\hookrightarrow', display: '\\hookrightarrow', desc: '↪ hook →' },
        { cat: 'Mũi tên', code: '\\longrightarrow', display: '\\longrightarrow', desc: '⟶ dài' },

        // === Sets & Logic ===
        { cat: 'Tập & Logic', code: '\\emptyset', display: '\\emptyset', desc: '∅ rỗng' },
        { cat: 'Tập & Logic', code: '\\mathbb{N}', display: '\\mathbb{N}', desc: 'ℕ tự nhiên' },
        { cat: 'Tập & Logic', code: '\\mathbb{Z}', display: '\\mathbb{Z}', desc: 'ℤ nguyên' },
        { cat: 'Tập & Logic', code: '\\mathbb{Q}', display: '\\mathbb{Q}', desc: 'ℚ hữu tỉ' },
        { cat: 'Tập & Logic', code: '\\mathbb{R}', display: '\\mathbb{R}', desc: 'ℝ thực' },
        { cat: 'Tập & Logic', code: '\\mathbb{C}', display: '\\mathbb{C}', desc: 'ℂ phức' },
        { cat: 'Tập & Logic', code: '\\forall', display: '\\forall', desc: '∀ với mọi' },
        { cat: 'Tập & Logic', code: '\\exists', display: '\\exists', desc: '∃ tồn tại' },
        { cat: 'Tập & Logic', code: '\\nexists', display: '\\nexists', desc: '∄ không tồn tại' },
        { cat: 'Tập & Logic', code: '\\therefore', display: '\\therefore', desc: '∴ do đó' },
        { cat: 'Tập & Logic', code: '\\because', display: '\\because', desc: '∵ bởi vì' },
        { cat: 'Tập & Logic', code: '\\vdash', display: '\\vdash', desc: '⊢ suy diễn' },
        { cat: 'Tập & Logic', code: '\\models', display: '\\models', desc: '⊨ mô hình hoá / thoả' },

        // === Calculus / Algebra ===
        { cat: 'Vi tích phân', code: '\\partial', display: '\\partial', desc: '∂ đạo hàm riêng' },
        { cat: 'Vi tích phân', code: '\\nabla', display: '\\nabla', desc: '∇ grad' },
        { cat: 'Vi tích phân', code: '\\sum', display: '\\sum', desc: '∑ tổng' },
        { cat: 'Vi tích phân', code: '\\prod', display: '\\prod', desc: '∏ tích' },
        { cat: 'Vi tích phân', code: '\\int', display: '\\int', desc: '∫ tích phân' },
        { cat: 'Vi tích phân', code: '\\iint', display: '\\iint', desc: '∬ tích phân kép' },
        { cat: 'Vi tích phân', code: '\\iiint', display: '\\iiint', desc: '∭ tích phân bội ba' },
        { cat: 'Vi tích phân', code: '\\oint', display: '\\oint', desc: '∮ đường cong' },
        { cat: 'Vi tích phân', code: '\\lim', display: '\\lim', desc: 'lim giới hạn' },
        { cat: 'Vi tích phân', code: '\\infty', display: '\\infty', desc: '∞ vô cực' },
        { cat: 'Vi tích phân', code: '\\sqrt{x}', display: '\\sqrt{x}', desc: 'căn bậc hai' },
        { cat: 'Vi tích phân', code: '\\sqrt[n]{x}', display: '\\sqrt[n]{x}', desc: 'căn bậc n' },

        // === Delimiters ===
        { cat: 'Ngoặc/Delimiters', code: '\\left( x \\right)', display: '\\left( x \\right)', desc: 'ngoặc tròn co giãn' },
        { cat: 'Ngoặc/Delimiters', code: '\\left[ x \\right]', display: '\\left[ x \\right]', desc: 'ngoặc vuông co giãn' },
        { cat: 'Ngoặc/Delimiters', code: '\\left\\{ x \\right\\}', display: '\\left\\{ x \\right\\}', desc: 'ngoặc nhọn co giãn' },
        { cat: 'Ngoặc/Delimiters', code: '\\left\\langle x \\right\\rangle', display: '\\left\\langle x \\right\\rangle', desc: '⟨⟩ góc' },
        { cat: 'Ngoặc/Delimiters', code: '\\left| x \\right|', display: '\\left| x \\right|', desc: 'trị tuyệt đối' },
        { cat: 'Ngoặc/Delimiters', code: '\\left\\| x \\right\\|', display: '\\left\\| x \\right\\|', desc: 'chuẩn (norm)' },
        { cat: 'Ngoặc/Delimiters', code: '\\left\\lceil x \\right\\rceil', display: '\\left\\lceil x \\right\\rceil', desc: '⌈ trần ⌉' },
        { cat: 'Ngoặc/Delimiters', code: '\\left\\lfloor x \\right\\rfloor', display: '\\left\\lfloor x \\right\\rfloor', desc: '⌊ sàn ⌋' },

        // === Accents ===
        { cat: 'Dấu/Accents', code: '\\hat{x}', display: '\\hat{x}', desc: 'mũ ^' },
        { cat: 'Dấu/Accents', code: '\\widehat{ABC}', display: '\\widehat{ABC}', desc: 'mũ rộng' },
        { cat: 'Dấu/Accents', code: '\\bar{x}', display: '\\bar{x}', desc: 'gạch trên' },
        { cat: 'Dấu/Accents', code: '\\overline{AB}', display: '\\overline{AB}', desc: 'gạch trên dài' },
        { cat: 'Dấu/Accents', code: '\\underline{x}', display: '\\underline{x}', desc: 'gạch dưới' },
        { cat: 'Dấu/Accents', code: '\\vec{v}', display: '\\vec{v}', desc: 'vector' },
        { cat: 'Dấu/Accents', code: '\\tilde{x}', display: '\\tilde{x}', desc: 'dấu ngã' },
        { cat: 'Dấu/Accents', code: '\\dot{x}', display: '\\dot{x}', desc: 'chấm trên' },
        { cat: 'Dấu/Accents', code: '\\ddot{x}', display: '\\ddot{x}', desc: 'hai chấm trên' },

        // === Misc ===
        { cat: 'Khác', code: '\\aleph', display: '\\aleph', desc: 'ℵ aleph' },
        { cat: 'Khác', code: '\\Im', display: '\\Im', desc: 'ℑ phần ảo' },
        { cat: 'Khác', code: '\\Re', display: '\\Re', desc: 'ℜ phần thực' },
        { cat: 'Khác', code: '\\ell', display: '\\ell', desc: 'chữ l cong' },
        { cat: 'Khác', code: '\\hbar', display: '\\hbar', desc: 'h gạch ngang' },
        { cat: 'Khác', code: '\\angle', display: '\\angle', desc: '∠ góc' },
        { cat: 'Khác', code: '\\measuredangle', display: '\\measuredangle', desc: '∡ góc đo' },
        { cat: 'Khác', code: '\\perp', display: '\\perp', desc: '⟂ vuông góc' },
        { cat: 'Khác', code: '\\top', display: '\\top', desc: '⊤ đúng' },
        { cat: 'Khác', code: '\\bot', display: '\\bot', desc: '⊥ sai' },
        { cat: 'Khác', code: '\\square', display: '\\square', desc: '□ ô vuông (logic)' },
        { cat: 'Khác', code: '\\blacksquare', display: '\\blacksquare', desc: '■ ô đen' },
        { cat: 'Khác', code: '\\S', display: '\\S', desc: '§ section' },
        { cat: 'Khác', code: '\\P', display: '\\P', desc: '¶ pilcrow' },
        { cat: 'Khác', code: '\\%', display: '\\%', desc: 'dấu % trong text' },
        { cat: 'Khác', code: '\\$', display: '\\$', desc: 'dấu $ trong text' },
        { cat: 'Khác', code: '\\#', display: '\\#', desc: 'dấu # trong text' },

        // === Spacing ===
        { cat: 'Khoảng cách', code: '\\,', display: '\\,', desc: 'mỏng' },
        { cat: 'Khoảng cách', code: '\\:', display: '\\:', desc: 'trung bình' },
        { cat: 'Khoảng cách', code: '\\;', display: '\\;', desc: 'hơi rộng' },
        { cat: 'Khoảng cách', code: '\\!', display: '\\!', desc: 'âm (thu hẹp)' },
        { cat: 'Khoảng cách', code: '\\quad', display: '\\quad', desc: 'rộng bằng 1em' },
        { cat: 'Khoảng cách', code: '\\qquad', display: '\\qquad', desc: 'rộng bằng 2em' }
    ];
